cgame: Fix warnings due to using memset on a non-trivial struct.
[ 36%] Building CXX object CMakeFiles/cgame-native-exe.dir/src/cgame/cg_animmapobj.cpp.o
/mnt/media/code/Unvanquished/src/cgame/cg_animmapobj.cpp: In function ‘void CG_AnimMapObj(centity_t*)’:
/mnt/media/code/Unvanquished/src/cgame/cg_animmapobj.cpp:152:33: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct refEntity_t’; use assignment or value-initialization instead [-Werror=class-memaccess]
  152 |  memset( &ent, 0, sizeof( ent ) );
      |                                 ^